name: Build Rocky 9 image (docker)
on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build Rocky 9 image (test)
    runs-on:
      - self-hosted
      - packer

    steps:
      - uses: actions/checkout@v4

      - name: Run build
        run: |
          sh -vx

          gid=$(getent group kvm | awk -F : '{ print $3 }')
          docker rm --force packer-rl9 || true

          docker build docker/packer-rl9 \
            --build-arg http_proxy \
            --build-arg https_proxy \
            --build-arg no_proxy \
            --build-arg KVM_GID=$gid \
            --tag infractl/packer-rl9

          docker run \
            --env http_proxy \
            --env https_proxy \
            --env no_proxy \
            --env PACKER_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            --device /dev/kvm --device /dev/fuse \
            --cap-add CAP_SYS_ADMIN --security-opt apparmor:unconfined \
            --name packer-rl9 infractl/packer-rl9 sh -c 'echo test'


